package ie.gmit.sw;

import java.util.Map;

/**
 * This class is used to take the user input and the maps generated by the
 * parsed files to swap the synonyms to the words.
 * 
 * @author Adil
 *
 */
public class UserInputMap {
	private Map<String, String> map;

	public UserInputMap(Map<String, String> map) {
		this.map = map;
	}

	/**
	 * This method takes the user input as String and swap the words which are
	 * synonym in the google file.
	 * 
	 * @Big_O_Notation This method runs in Linear time because it loops over the
	 *                 each item in the map one by one.
	 * 
	 * @param text User input
	 * @return Returns the text back but with swapped synonyms.
	 */
	public String swapping(String text) {
		String[] words = text.split(" ");
		StringBuilder sb = new StringBuilder();
		for (String word : words) {
			// swap the words here
			String value = map.get(word.toLowerCase().replaceAll("[^A-Za-z0-9 ]", ""));
			if (value != null) {
				sb.append(ConsoleColour.RED + value + " " + ConsoleColour.RESET);
			} else {
				sb.append(word.toLowerCase().replaceAll("[^A-Za-z0-9 ]", "") + " ");
			}
		}
		return sb.toString();
	}
}